name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "relese" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust Targets
      run: rustup target add aarch64-apple-darwin aarch64-pc-windows-msvc aarch64-pc-windows-gnullvm i586-pc-windows-msvc i586-unknown-linux-gnu i586-unknown-linux-musl i686-pc-windows-gnu i686-pc-windows-gnullvm i686-pc-windows-msvc i686-unknown-freebsd i686-unknown-linux-gnu i686-unknown-linux-musl x86_64-apple-darwin x86_64-pc-windows-gnu x86_64-pc-windows-gnullvm x86_64-pc-windows-msvc x86_64-unknown-freebsd x86_64-unknown-linux-gnu x86_64-unknown-linux-gnux32 x86_64-unknown-linux-musl x86_64-unknown-linux-ohos x86_64-unknown-netbsd
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
