name: Rust Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "relese" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Linux build deps
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev libfreetype6-dev libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          check-latest: true
          update-environment: true
      - name: Add Python to PATH manually (Unix)
        run: echo $Python_ROOT_DIR >> $GITHUB_PATH

      - name: Setup Rust Targets
        run: rustup target add x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build #--verbose
      - name: Run tests
        run: cargo test #--verbose
      - name: Check if the README is up to date.
        run: |
          cargo install cargo-rdme
          cargo rdme --check